# Server port
server.port=8761

# Eureka Server configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Server name
spring.application.name=discovery-server

# Disable self-preservation mode for development
eureka.server.enable-self-preservation=false 